### ISSUE TITLE
Add support for versatile attacks & multi-attacks

### ISSUE THREAD

**Issue by Merudo** [Stendarpaval/mob-attack-tool#11]
It would be nice if the mob units could use versatile attacks if they use a weapon two-handed, and for multiattack to be automated.

**Comment by Stendarpaval** [comment]
I've had a look at automatically adding a versatile weapon option. It's not as easy as I thought, but I'll keep tinkering with it later.

As for multiattack, you're in luck: I just released [v0.1.19](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.19), which adds the ability to use multiattack in Mob Attack Tool. 

Automatic detection of how many weapons to use will have to wait for another day, since coming up with an algorithm that correctly extracts that information from all the permutations of Multiattack item descriptions is a bit too time-consuming for now.

**Comment by Merudo** [comment]
[Midi-qol](https://gitlab.com/tposney/midi-qol) has an option to hold "shift" before attacking so that the attack is considered versatile. Maybe it's worth checking out the code?

**Comment by Stendarpaval** [comment]
I decided to work on automating multiattacks, and that is out now with [v0.1.20](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.20). Make sure to go to Mob Attack Tool's settings after updating the module to turn this autodetect and select feature on. 

I *did* look around in Midi-QOL's repo and saw odds and ends of how they use events for key detection... It's quite new to me, however, and I have an internship to finish. I think I might be able to squeeze in a different solution for versatile damage in a few days' time. Might take longer, though. Planning is hard, haha

**Comment by Stendarpaval** [comment]
So, it took a bit longer than "a few days'  time", but as of [v0.1.23](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.23), Mob Attack Tool properly supports versatile damage. 

Since automatic multiattack support was added previously, I think I will close this issue. Thanks for making Mob Attack Tool a better module! Let me know (in a new issue) if you have any other suggestions for how to improve this module.
