### ISSUE TITLE
Feature request: Roll Dice So Nice 3D dices on Atack Rolls

### ISSUE THREAD

**Issue by giandoso** [Stendarpaval/mob-attack-tool#13]
During mass rolls, would be nice to also see the 3d dices on the attack rolls, not only on damage...

**Comment by giandoso** [comment]
this snippet could be useful: 
` 
if (game.dice3d) {
    for (let i = 0; i < rollArray.length; i++) {
        if (i === rollArray.length - 1) await game.dice3d.showForRoll(rollArray[i]);
        else game.dice3d.showForRoll(rollArray[i]);
    }
  }
`

Source: https://github.com/jessev14/Multiattack-5e/commit/f482d0e13b1c2945f65d38c37d83c13689636bf0

**Comment by Stendarpaval** [comment]
If you enable to "Show Individual Attack Rolls" setting, then Dice So Nice dice should be rolled for attack rolls. This only happens if you also use the "Individual Rolls" setting, instead of "Mob Rules", because there aren't any actual attack rolls in case of the latter.

So, just to make sure, do the 3d dice roll for you when you enable these settings? If not, then this might be a bug I need to fix.

**Comment by Stendarpaval** [comment]
I'm going to close this issue. Please reopen it if you still encounter bugs related to this.
