### ISSUE TITLE
Feature request: Show all attack rolls in chat with only Midi QoL enabled

### ISSUE THREAD

**Issue by NateHawk85** [Stendarpaval/mob-attack-tool#17]
With only Midi QoL enabled, allow GMs to view all attack rolls made by the mobs when Show Individual Attack Rolls is enabled. 

![image](https://user-images.githubusercontent.com/7596412/118872158-e07be100-b8ad-11eb-8a4d-9758e379c273.png)

Could also potentially display their +to hit bonuses as well... :) This would be especially useful as if a player adds a modifier to their AC mid-mob (like the Shield spell in D&D5e, for example), it registers all hits with the old AC, not the new AC. There isn't really a workaround to this, as far as I can tell.

Love the module, by the way. I've only used it for a week, but it's already opened my options as a GM to allow for a wider selection of encounters, and mobs of low-CR enemies is a MUCH faster process. Great work on this!

**Comment by Stendarpaval** [comment]
Glad to hear you like it! I've always intended to add support for showing successful attack rolls when only using midi-qol, but I never got around to it. Your issue spurred me to do so, which led me to work on it and just now release [v0.1.32](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.32), which should pretty much add what you requested. 

Let me know if it works! 

By the way, I can imagine an automated solution to the Shield issue, but it's rather complicated. It would involve storing the attack and damage data until the next mob attack, and then add a (collapsable) section to the results chat message with buttons next to each attack and then add html listeners to these chat message buttons to have them update the (also stored) target's AC and then reexamine if the attacks following that one, possibly even correcting the target's HP. 

So there's a path to an automated solution, but it would require a lot of changes to be made. And I'd need to learn how to add html event listeners to chat messages in the first place, haha.

**Comment by NateHawk85** [comment]
That looks great! I just updated and enabled Show Individual Attack Rolls and got the following:

![image](https://user-images.githubusercontent.com/7596412/119065976-56627400-b9a4-11eb-9dc1-ed7f32f55ea5.png)

Not to get too picky here, but one thing that _might_ be nice is to highlight natural 20's in green and nat 1's in red?

Another option that could be useful is to show _all_ attack rolls, whether they hit or miss. 

But anyhow, thank you so much for addressing that quickly! No worries on the shield automation - now that that's implemented, it's super easy to calculate that manually. Thank you!

**Comment by Stendarpaval** [comment]
Sure, I think I'll add a setting for also showing attack rolls that didn't succeed. I didn't do so initially because keeping the message compact makes it easier to use during combat encounters, but adding options won't be too hard. 

I've been looking into the html and css of Core Foundry's dice rolls and will likely mimic how it displays dice roll results. That should also make maximum rolls / natural 20s green and minimum rolls / natural 1s red. 

The `+x to hit` bonus is currently already visible if you hover your cursor over the d20 icon. I've experimented with showing it in the same line as the results, and Mob Attack Tool actually used to do that several releases ago. 

<details>
  <summary>Click here to show a screenshot from such an older release.</summary>

  <img width="1185" alt="screenshot_mat_7_individual_rolls_betterrolls_idi" src="https://user-images.githubusercontent.com/17188192/113694151-ad033f80-96cf-11eb-8b11-7f61bd594ae6.png">
</details>

It takes up a relatively large amount of space in the results message, though. That's why I opted for the tooltip / cursor hover method for v0.1.32. Maybe I'll come across a better method while working with the html and css of Core Foundry, as mentioned above. 

And I don't mind adding a setting to specifically enable/disable Dice So Nice rolls. Issue #13 shows that it might be clearer to users that there is support for it, and that way they'll have more control over it. 

I don't have time today to work on this, not sure about this weekend either, but I'll probably get around to it sometime next week. :)

**Comment by NateHawk85** [comment]
I definitely agree with that logic. No worries! Personally, I do like seeing the legacy Target/Attack Bonus icons, but that's just my personal preference. Regardless, thank you so much for including all the successful rolls into the chat card! And I just checked out the hover functionality, and that's perfect :)

**Comment by Stendarpaval** [comment]
I just released [v0.2.0](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.2.0), which alongside some other bugfixes and Core compatibility focuses on the improvements discussed in this issue. 

Nat 20s and 1s are now colored differently, and you can choose to show unsuccessful rolls as well (which also look different). In the limited time I have today I was unable to find a satisfying way to include the `+x to hit` text anywhere else, so for now that'll remain as text that you can show by hovering the cursor over the rolls. 

Like previously, please download and let me know if everything works on your end. Also, I quite enjoyed working on your suggested improvements. If you have any other suggestions, please don't hesitate to tell me. :)

**Comment by NateHawk85** [comment]
I love the Nat 20/1 adjustment! That's perfect, thank you for that!

I checked out the Dice So Nice setting changes. Just from some initial testing, it looks as though the setting doesn't affect whether or not Dice So Nice rolls are actually rolled. However, this could be a module compatibility thing with something else I have enabled, so I can do some additional testing later and see what I can find on that. Here's a screenshot of my relevant Mob Attack Tool settings, if it helps at all:
![image](https://user-images.githubusercontent.com/7596412/119683946-b70d0900-be09-11eb-851d-52f2c00aa3f8.png)

And the result:
![image](https://user-images.githubusercontent.com/7596412/119683955-b96f6300-be09-11eb-9f1c-8ec0a4049b47.png)

Thank you again for being so responsive on these feature requests! :)

**Comment by Stendarpaval** [comment]
You know, now that I think about it... I don't think I actually did anything with the new setting except for registering it. I completely forgot to change anything to respect the new setting, haha! I don't actually use Dice So Nice myself, so I forgot to test it... How embarrassing. It's kinda late now, but I'll fix this soon.

**Comment by Stendarpaval** [comment]
Alright, [v0.2.1](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.2.1) is released, which should fix the Dice So Nice option. Let's hope I didn't forget anything this time. 🤞

**Comment by Stendarpaval** [comment]
So [v0.2.2](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.2.2) makes more changes to the Dice So Nice option. Unfortunately, all it does now is basically turn off Dice So Nice without deactivating Dice So Nice. The only benefit over actually deactivating it, is that changing Mob Attack Tool's setting doesn't trigger a reload. 

That can be helpful, but also frustrating to users who disable that option at one time and then have forgotten about that when they actually want Dice So Nice to roll 3d dice. So I might fully remove it in a later release, just to keep things clean. I recommend changing Dice So Nice's settings to not show 3d dice during combat instead. 

However, upon rereading the comment where you brought this up I realized that you might have just wanted an option to stop 3d dice from being rolled for attack rolls, since DMs might want to keep the results a secret. Even if that isn't what you wanted, I'll add that option in an upcoming release and then close this issue. :)

**Comment by Stendarpaval** [comment]
Alright, [v0.2.4](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.2.4) is out and in fact already in [v0.2.3](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.2.4) the extra option was added that prevents 3d dice rolling for attack rolls when GMs use Mob Attack Tool. 

Thus I'll close this issue. Feel free to reopen it if you encounter any problems!
