### ISSUE TITLE
Multiattack parsing improvement: better recognition for "The X makes three attacks: one with its bite and two with its claws"

### ISSUE THREAD

**Issue by Merudo** [Stendarpaval/mob-attack-tool#38]
The Yuan-ti Broodguard (VGM, page 203) has the following multiattack text:

`Multiattack. The broodguard makes three attacks: one with its bite and two with its claws.`

The Mob Attack tool doesn't seem to recognize the multiattack, and only selects a single bite attack:

![image](https://user-images.githubusercontent.com/7371085/133929078-fb22a22e-da21-4723-be48-a1c40620c1bd.png)

The same happens with the Red Young Dragon:

![image](https://user-images.githubusercontent.com/7371085/133929188-6b7e097d-3a56-48ee-aa2f-8fa7463f1dbd.png)

Other creatures affected include various Dragons, Slaad, Deinonychus, Dragon Turtle, Troglodyte, Manticore, Troll, etc.

It seems like the `and` keyword is not taken into account. It would be great if these multiattacks were recognized properly.

**Comment by Merudo** [comment]
There is also 

- `The X makes two attacks: one with its bite and one with its claws.` (Giant Badger, Black Bear)
- `The X makes two attacks: one with its Y and one with its Z.` (Balor with it's sword and whip, Blood Witch with its long and short swords).
- `The troll makes six attacks: one with its bite and five with its claws.` (Five-Armed Troll)

**Comment by Stendarpaval** [comment]
Thanks for looking into this!

The algorithm that parses multiattack options indeed doesn't look at `and`, but it shouldn't have to. It looks at the total number of attacks and the number of specific (named) weapons, and then selects those. 

However, the algorithm definitely isn't perfect. You can read more about that in issue #18.

Having said that, I _did_ explicitly test the algorithm on the Young Red Dragon during development, and it properly selects the bite and claw attacks. I just checked, and in my test world it still does:

<img width="722" alt="Screenshot Young Red Dragon MAT" src="https://user-images.githubusercontent.com/17188192/133940043-aa68d6ac-e68c-4d9a-8831-b612084accf9.png">

This Young Red Dragon actor was pulled directly from the Monsters SRD compendium of the dnd5e system, with only the actor and token image (and token size) corrected afterwards. 

The Yuan-ti Broodguard, Slaadi, Deinonychus and Troglodyte aren't part of the Monsters SRD, so I can't verify whether these'd work on my end. Did you recreate these actors by hand, or did you import them from Roll20 or DNDBeyond? 

- The Dragon Turtle is part of the SRD however, and indeed something funny is going on with the number of attacks as well as the fact that the tail attack is selected while it should be detected as an option and therefore unselected. Something to look into.

- The Manticore's Tail Spike should be listed as three attacks and not already be selected, like the Dragon Turtle's tail attack. The incorrect number is likely because the three attacks are already accounted for by the one bite and two claw attacks. Probably another exception to account for in the algorithm.

- The Troll from the SRD works fine on my end, though, as you can see here:

<img width="697" alt="Screenshot Troll MAT" src="https://user-images.githubusercontent.com/17188192/133940388-bb269f31-89c4-4995-95d7-2e90e198d7b8.png">

- The Giant Badger also works fine on my end (I won't bore you with further screenshots)
- The Black Bear also works fine on my end
- The Balor also works fine on my end (longsword and whip)

The Blood Witch and Five-Armed Troll aren't part of the SRD, so I can't test these either. 

---

I suspect that you're using monster actors that aren't part of the SRD and which might have some unexpected (and perhaps invisible) characters in the multiattack description text that Mob Attack Tool has trouble to parse. 

I say that, because in situations where Mob Attack Tool can't parse any multiattack options, it will select the weapon that can deal the most max damage. From your screenshots, it appears that's what it's doing.

As for the potential improvements the algorithm I mentioned earlier, I'm afraid I'm a little short on development time these days, so it could take some time until I get around to it.

**Comment by Merudo** [comment]
I found out the cause: at the end of the multiattack description, there were extra blank lines. In HTML, those were

```html
<p>&nbsp;</p>
<p>&nbsp;</p>
```

Removing these lines, fixed the issue.

**Comment by Merudo** [comment]
I've added PR #39 which removes html tags, whitespaces, and the `&nbsp;` symbol from the Multiattack description before parsing.

The code for removing html tags was taken from [here](https://css-tricks.com/snippets/javascript/strip-html-tags-in-javascript/).

The PR completely fixed my issues with Multiattack not getting parsed correctly.
