### ISSUE TITLE
Dice-So-Nice-Rolls also for Players

### ISSUE THREAD

**Issue by veithflo** [Stendarpaval/mob-attack-tool#47]
Hi there,

I'm using Dice-so-nice and Better-Rolls and I've found an wrong api-call why the 3d-dices are not shown for my players.

It's due to missing parameters for `game.dice.showForRoll(...)` in several places within your code.
For example in _individualRolls.js:72_:
```
//Your code
if (!game.settings.get(moduleName, "hideDSNAttackRoll") || !game.user.isGM) game.dice3d.showForRoll(attackRoll);

//With parameters for synchronize
if (!game.settings.get(moduleName, "hideDSNAttackRoll") || !game.user.isGM) game.dice3d.showForRoll(attackRoll, game.user, true);
```
API Documentation for `game.dice.showForRoll(...)`: [https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/API/Roll#using-the-fvtt-roll-class](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/API/Roll#using-the-fvtt-roll-class)

I've changed it on all places in your module and now the dice are rolling also for my players. :-)

I guess you want to make it more flexible like i did. Checking the current selected Roll-type (private, public) or making an [Roll Public] and [Roll Secret] button with different rolls. That would be the best solution at all i think. The nasty wizard with his shield spell shouldn't know all rolls at once, he should decide roll for roll when to activate his shield. Therefore i roll them individually if it's against him, not with the mob-attack. With the better implementation, i would be able to use both of it.

**Comment by Stendarpaval** [comment]
Thank you for reporting this bug! I'm a bit late in addressing it, but better late than never. I'm leaning to checking the currently selected roll mode rather than adding more buttons. So in the next release, the DSN animation of the GMs mob attack rolls should be visible to players if the GMs roll mode is set to public. Otherwise, only the GM will see the animation. Of course, the "Hide 3D dice for GM attack rolls" setting also needs to be disabled for the animations to be shown.

**Comment by Stendarpaval** [comment]
As you can read in [v0.3.13's release notes](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.13), I implemented the fix you suggested. I only just now checked to see if this also works on Foundry Core 0.8.9, but apparently back then the roll mode for public rolling was called `'roll'`, while in V9 it's called `'publicroll'` - and that's the only case v0.3.13 will check for. So if you're still on Foundry 0.8.9, the new release of Mob Attack Tool won't fix the DSN issue. 

It's easy to fix and I'll definitely will in the next patch (it's literally checking for both cases rather than just one), but I'll wait a day to see if other people report other problems so that I can address these together in one larger patch rather than multiple tiny ones.

**Comment by veithflo** [comment]
Don't worry about that few days delay. Spending your time making and maintaining this addon is something you do voluntary. So thank you for your time and your work. And guess what, I think there are many people out there liking your addon. :-)

Back to topic. I agree with the decision to link it onto the selected roll-type for the same reasons you did. In the meantime i've upgraded to Foundry v9 so i'm good with fixing it for v9. I keep the issue open as you might want it as a reminder to implement the downwards compatible if-statement on the next release.

Happy new year.

**Comment by veithflo** [comment]
Added your downwards-compatibility with "roll" for v0.8.9 and the missing second place for damage-rolls via DiceSoNice via pull-request #50
