### ISSUE TITLE
Multiple Targets and Better Rolls/Midi-QOL

### ISSUE THREAD

**Issue by HydrallUrakan** [Stendarpaval/mob-attack-tool#49]
I've been fiddling around with the Foundry V9 version of the module, and overall it's working great - but I've noticed that there's some slightly odd functionality when it comes to multiple actors attacking multiple other actors.

When only using Midi-QOL, it works perfectly fine; the correct targets will receive the correct attacks. However, when run while Better Rolls is also enabled, something in how one of these modules is handling targeting gets confused; all targeted tokens are made the target of the combined attacks, leading to some strange-looking situations.
![image](https://user-images.githubusercontent.com/94702225/147579720-9c469ff4-4dff-4ddc-a9c6-47c770589993.png)

I've tried immediately deselecting all targets after making the attacks, and that just makes nobody get hit.

I'm not sure if this is even an issue that can be fixed necessarily, or if it's one that BR would need to fix - or some combination of all three. Fortunately, multiple tokens attacking one target still works fine, but it would be nice to be able to have both.

**Comment by Stendarpaval** [comment]
Ah, I haven't tested using *both* Midi-QOL and Better Rolls for 5e in quite some time. Using these modules simultaneously has often caused subtle issues in the past and the general advice over at Foundry's official Discord server was to use one or the other. But that was a few months ago, things might be different now. 

In any case, here's what Mob Attack Tool does when both Midi-QOL and Better Rolls for 5e are active: it will use Better Rolls for 5e for the damage cards, pretty much ignoring anything related to Midi-QOL. That means that what you're seeing here is how Midi-QOL reacts to the Better Rolls for 5e damage card, which is essentially a single attack (the only one that hit) that would hit the AC of each currently targeted token (since they're all guards with the same AC). Even if there were multiple hits, these would probably be combined into a single damage card with your current settings, ending up with the same result. 

There's no real way of fixing this from Mob Attack Tool's end alone, since it can't tell Better Rolls for 5e which target is associated with which successful hit in a way that Midi-QOL would pick up on. 

However, I *can* recommend that you go into the "Modules" tab of Mob Attack Tool's Advanced Settings and then disable the "Enable Better Rolls for 5e" setting. That will force Mob Attack Tool to use Midi-QOL for attack and damage rolls. It will look slightly different, but it should solve your problem. 

Please give that a try and let me know if it works okay for you, so that we can close this issue afterwards. :)

**Comment by HydrallUrakan** [comment]
Indeed, I should probably give up on one of the two, but I enjoy both the automation and the fancy roll cards... 

In any case, that did fix things! Thank you!

**Comment by Stendarpaval** [comment]
I can understand the temptation! Glad that the solution fixed it (mostly). I'll go ahead and close this issue :)
