### ISSUE TITLE
Feature Request: Expose to players

### ISSUE THREAD

**Issue by AdamSturge** [Stendarpaval/mob-attack-tool#8]
It would be nice if there was a configuration option to expose mob attack features to players. I have a necromancer in my game that has a bunch of zombies. I can export macros and let them use them but Ideally they could decide on the fly how many zombies to use instead of me having to export a macro for every possibility.

**Comment by Stendarpaval** [comment]
I can see how necromancers could make good use of mob attacks, so I'll definitely add a way to allow players to use Mob Attack Tool (without showing target AC). 

Technically you could already achieve this by editing an exported macro, since it already exposes how many mob attackers use how many weapon attacks. But it's probably a better user experience to use the tool itself, which is why I'll try to add it sometime this week.

**Comment by Stendarpaval** [comment]
As you can read in release [v0.1.13](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.1.13), Mob Attack Tool  now has the option to allow players to use it. 

I'll close this issue for now, but let me know if you run into any issues. :)
